sonar.projectKey=traicasolutions_devops
sonar.projectName=devops
sonar.organization=traicasolutions
sonar.projectVersion=1.0

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/dist/**
sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
